[package]
name = "gpui-app"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_macros = { git = "https://github.com/zed-industries/zed" }
anyhow = "1.0.86"
unicode-segmentation = "1.10"
smallvec = "1.13.2"
